### PR TITLE
feat: beautiful TUI round 3

### LINKED ISSUE #182: Spike: experiment with adding charm viewport to display zarf output when deploying bundle
### Is your feature request related to a problem? Please describe

To reduce the amount of data the terminal outputs and the amount of scrolling user must do to see the status of package deployments, we want to experiment with adding a viewport component to allow the user to view all of the zarf output if they want to but reduce the space the output takes in the terminal.

Keep zarf output formatting the same for now.

### Describe the solution you'd like

- **Given** a user has deployed a bundle
- **When** a package is being deployed,
- **Then** print the zarf output into a viewport component 

### Additional context

Charm Viewport component - -View SBOMs after deployment with this command:
$ zarf package inspect -s <package-name>.tar.zst

Sketch - 
IMG_5058

Figma mock up - 
Screenshot 2023-11-08 at 3 29 29 PM

### PR DESCRIPTION
**Pull request by UncleGedd**
## Description

- adds BubbleTea
- adds `no-tea` flag
- adds `uds logs`
- adds retries to `uds publish`

### CODE REVIEW

**Comment by UncleGedd** [comment]
image

**Comment by UncleGedd** [comment]
image

**Comment by Racer159** [comment]
Just plugging my bug in this work :wink: https://github.com/defenseunicorns/uds-cli/issues/516

**Review by decleaver — APPROVED** [review]
pair reviewed. appreciate you dealing with the charm/tui learning pains for us! ❤️

**Pull request merged**
