### PR TITLE
chore: remove uds-runtime (ui)

### PR DESCRIPTION
**Pull request by catsby**
## Description

This PR removes the embedded UDS Runtime component, and subsequently the `uds ui` command. We're reevaluating how we want the two projects to work together and decided for now it's best to remove it. 

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Review by mjnagel — DISMISSED** [review]

**Review by mjnagel — COMMENTED** [review]
LGTM, not sure if @UncleGedd or @decleaver might want to take a glance quickly.

**Comment by decleaver** [comment]
quick glance, looks good. Have a leftover var in lang.go though `CmdUIShort`

**Comment by catsby** [comment]
@decleaver thanks, I cleaned that up and noticed a few more stragglers which I removed in 2ac52012fde17e let me know what you think

**Review by decleaver — APPROVED** [review]
🚀

**Review by mjnagel — APPROVED** [review]

**Pull request merged**
