### PR TITLE
chore: update linting configuration

### LINKED ISSUE #624: Investigate dead code automation
## Description

Ensure we are using automation to detect dead code. Dead code should ideally break CI

For example: https://github.com/defenseunicorns/uds-cli/blob/1fb7bb0fec9eb7c0a980802ab5223d72d5f77a63/src/pkg/bundle/tarball.go#L282

### PR DESCRIPTION
**Pull request by TristanHoladay**
## Description
Update golangci-lint / pre-commit configuration to catch more unused variables, dead / unreachable code etc...

## Related Issue

Resolves #624 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Comment by TristanHoladay** [comment]
Looking at the zarf lint workflow and their [`.golangci.yaml`](https://github.com/defenseunicorns/zarf/blob/main/.golangci.yaml) i noticed they're making use of golangci-lint for `revive`. @UncleGedd is this something we want to mimic, instead of using the revive step in our [`scan-lint` workflow](https://github.com/defenseunicorns/uds-cli/blob/db6f3db180a057e81a86c37e670fd6f6747141b9/.github/workflows/scan-lint.yaml#L28)

**Comment by TristanHoladay** [comment]
current turned on linters for golangci-lint

`golangci-lint linters`

```
errcheck: errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases [fast: false, auto-fix: false]
gofmt: Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification [fast: true, auto-fix: true]
goimports: Check import statements are formatted according to the 'goimport' command. Reformat imports in autofix mode. [fast: true, auto-fix: true]
gosec: Inspects source code for security problems [fast: false, auto-fix: false]
gosimple: Linter for Go source code that specializes in simplifying code [fast: false, auto-fix: false]
govet: Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes. [fast: false, auto-fix: false]
ineffassign: Detects when assignments to existing variables are not used [fast: true, auto-fix: false]
nilerr: Finds the code that returns nil even if it checks that the error is not nil. [fast: false, auto-fix: false]
staticcheck: It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary. The author of staticcheck doesn't support or approve the use of staticcheck as a library inside golangci-lint. [fast: false, auto-fix: false]
unused: Checks Go code for unused constants, variables, functions and types [fast: false, auto-fix: false]
```

**Comment by UncleGedd** [comment]
Really great work on this, love seeing all that red

**Review by UncleGedd — APPROVED** [review]
🚀

**Pull request merged**
