### PR TITLE
feat: beautiful TUI

### LINKED ISSUE #182: Spike: experiment with adding charm viewport to display zarf output when deploying bundle
### Is your feature request related to a problem? Please describe

To reduce the amount of data the terminal outputs and the amount of scrolling user must do to see the status of package deployments, we want to experiment with adding a viewport component to allow the user to view all of the zarf output if they want to but reduce the space the output takes in the terminal.

Keep zarf output formatting the same for now.

### Describe the solution you'd like

- **Given** a user has deployed a bundle
- **When** a package is being deployed,
- **Then** print the zarf output into a viewport component 

### Additional context

Charm Viewport component - -View SBOMs after deployment with this command:
$ zarf package inspect -s <package-name>.tar.zst

Sketch - 
IMG_5058

Figma mock up - 
Screenshot 2023-11-08 at 3 29 29 PM

### PR DESCRIPTION
**Pull request by UncleGedd**
## Description
Limitations
- The Zarf code that runs when deploying the init pkg is turning pterm output back on

## Related Issue

Fixes #182

### CODE REVIEW

**Comment by Madeline-UX** [comment]
@UncleGedd Came here to see if I could view pretty new progress bars.

**Comment by UncleGedd** [comment]
WIP: https://vhs.charm.sh/vhs-6TGIr2QSb0kW8UC1GnUNuJ.gif

**Comment by UncleGedd** [comment]
image

**Comment by UncleGedd** [comment]
Loooong running PR here, going to close the PR but keep the branch around as an example of progress bars

**Pull request closed without merging**
