### PR TITLE
Add ghcr package test

### PR DESCRIPTION
**Pull request by anthonywendt**
Closes https://github.com/defenseunicorns/uds-cli/issues/43

### CODE REVIEW

**Comment by anthonywendt** [comment]
This 403 Unauthorized error seen in the failed action is interesting. Not sure whats going on.

I can run this no issue on my ec2 linux x86 machine with my github creds. Pulls the init package and can build the bundle no problem.

When I run it on my arm mac I get this same 403 Unauthorized with my creds. When I set a bogus credential I get a 401 denied instead. 

Screenshot 2023-09-02 at 5 06 40 PM

**Comment by anthonywendt** [comment]
> This 401 Unauthorized error seen in the failed action is interesting. Not sure whats going on.
> 
> I can run this no issue on my ec2 linux x86 machine with my github creds. Pulls the init package and can build the bundle no problem. If I set a bogus cred I get a 403 denied error instead.
> 
> When I run it on my arm mac I get this same 401 Unauthorized with my creds. When I set a bogus credential I get a 403 denied instead.
> 
> Screenshot 2023-09-02 at 5 06 40 PM

Figured out its the --insecure flag that is causing issues. Investigating what to do.

**Comment by anthonywendt** [comment]
Relevant comments in issue https://github.com/defenseunicorns/uds-cli/issues/43

**Review by UncleGedd — COMMENTED** [review]
Great work on this! Are the additions to `go.mod` required or can we remove those for this PR?

**Comment by anthonywendt** [comment]
> Great work on this! Are the additions to `go.mod` required or can we remove those for this PR?

It probably okay to remove? Its an artifact of getting things working for me to debug in vscode. Is there a reason to not to keep the updates?

**Review by UncleGedd — APPROVED** [review]
Awesome work, thanks again!

**Pull request merged**
