### PR TITLE
update go version for ci

### PR DESCRIPTION
**Pull request by corang**

### CODE REVIEW

**Comment by UncleGedd** [comment]
Hey thanks for this @corang , could you also make the update in `go.mod` (and any other references to that old version of Go that I'm not thinking of)?

**Comment by corang** [comment]
tbh I don't really know how to do that, is it just updating the value in the `go.mod`?

**Comment by UncleGedd** [comment]
> tbh I don't really know how to do that, is it just updating the value in the `go.mod`?

Yep exactly, just bump the version in the `go.mod` and run `go mod tidy` (not sure if the `go mod tidy` will actually change anything but we'll all need to do it anyway)

**Review by UncleGedd — APPROVED** [review]
thank you!!

**Pull request merged**
