### PR TITLE
flattens task yaml structure

### PR DESCRIPTION
**Pull request by UncleGedd**
Removes `name` key under an `[]actions.task`, new syntax is:
```
actions:
  - task: name-of-task
```

### CODE REVIEW

**Review by mjnagel — APPROVED** [review]

**Comment by mikevanhemert** [comment]
How does this support or impact the ability to reference tasks that are remote?

For instance, I may define a set of tasks that are universally use across a suite of repositories (stand up a cluster, tear down a cluster, etc) and instead of copy-pasting those tasks reop-to-repo, prefer to keep things DRY. It seems to me the older schema may have afforded that evolution better this update.

**Comment by jeff-mccoy** [comment]
I love the shorthand, but would be good to understand our intentions with remote tasks as I don't fully know what they would be yet.

**Comment by mikevanhemert** [comment]
> I love the shorthand, but would be good to understand our intentions with remote tasks as I don't fully know what they would be yet.

Entirely possible that I'm behind in my understanding of things. There were some early discussions surrounding DRY with whatever task running we do. Could I create a handful of tasks that are useful to many repos, stick them in one location, _and_ use them for both CI and local development? That would be very powerful

**Comment by mikevanhemert** [comment]
With the current PR, it might be this easy

```
#local task
- name: a-task
  actions:
    - task: local

- name: local
  actions:
    - cmd: echo "hello local"
...
# remote task
actions:
  - task: remote
    ref: https://raw.githubusercontent.com/defenseunicorns/uds-cli/b923cba25730bb487f2e619a0b58d4b9141adecd/src/test/tasks.yaml
```

**Comment by UncleGedd** [comment]
I created a [follow up ticket](https://github.com/defenseunicorns/uds-cli/issues/151) to support remote task files, if that's something we think we need today I can create a follow-on PR or we can let that issue simmer for a bit

**Comment by zachariahmiller** [comment]
> With the current PR, it might be this easy
> 
> ```
> #local task
> - name: a-task
>   actions:
>     - task: local
> 
> - name: local
>   actions:
>     - cmd: echo "hello local"
> 
> ...
> 
> # remote task
> actions:
>   - task: remote
>     ref: https://raw.githubusercontent.com/defenseunicorns/uds-cli/b923cba25730bb487f2e619a0b58d4b9141adecd/src/test/tasks.yaml
> ```
> 
> So the flattened syntax remains, but there's a way to reference remote tasks if desired

While i agree this works, it becomes pretty verbose is a remote file of (common) tasks or even just another file with common tasks in a different directory is pulled in.

What seems much nicer is this sort of syntax with
```yaml
include:
   common: ./extra-tasks.yaml
tasks:
  - task: local-task
  - task: common:remote-taske
``` 

see https://github.com/defenseunicorns/JosueAvena/blob/b318483bd1364540747e8b519fcf8c12158a9750/Taskfile.yml#L40

**Comment by UncleGedd** [comment]
^^ added @zachariahmiller 's suggested syntax to that follow-on ticket as well

**Review by decleaver — APPROVED** [review]
Do it. (looks good)

**Pull request merged**
