### PR TITLE
fix: toctou for files

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Fixes https://github.com/defenseunicorns/uds-cli/issues/440

## Description

toctou for files

## Related Issue

Fixes #
 https://github.com/defenseunicorns/uds-cli/issues/440

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
> I'm not sure this actually prevents any attacks on the files in the temp dir, it just makes it much harder. The attacker would have to maliciously change the file after verification, and restore it before the second verification.
> 
> There are even some ways the attacker could win these races pretty easily. Like, do an early replacement of index.json with a symlink (before any reads or verification of it). And if they pointed into an attacker-controlled file on a FUSE volume, they could control what individual reads return.
> 
> I think the right way to do tmpdir security is probably just UNIX file permissions? Create a single randomly named subdirectory of /tmp (or wherever the OS specifies) and restrict permissions to something like 0700. If the user uses --tmpdir, it's on them to make sure that's a secure location.

I appreciate the detailed feedback and wasn't unaware of the FUSE volume issue. Thank you! I have implemented the changes. 

Please look at it and let me know.

**Review by bburky — CHANGES_REQUESTED** [review]
uds-cli has a `--tmpdir` flag, this path should be used if configured. Only use `os.TempDir()` if it is not set.

I still don't think checksums add any security. An attacker modifying files be prevented by file permissions. Checksums at best can only detect changes, but are still prone to race conditions and can be bypassed by an attacker. Secure permissions should prevent the attacker entirely.

**Review by bburky — APPROVED** [review]
LGTM

**Review by UncleGedd — APPROVED** [review]
Looks great. Appreciate the additional feedback @bburky 🚀

**Pull request merged**
