### PR TITLE
fix: zarf optional component negation

### PR DESCRIPTION
**Pull request by rjferguson21**
## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-cli/blob/main/CONTRIBUTING.md)(https://github.com/defenseunicorns/uds-template-capability/blob/main/CONTRIBUTING.md#submitting-a-pull-request) followed

### CODE REVIEW

**Comment by UncleGedd** [comment]
Chatted with @zachariahmiller to get more context on this. @rjferguson21 would you like to implement the `overrides.<component>.enabled` syntax? (no pressure!)

**Comment by UncleGedd** [comment]
Context so I don't forget again: the team is requesting the ability to override the `required` key of a Zarf pkg component. In other words, regardless of whether component is `required` in a `zarf.yaml`, bundle authors have the ability to `enable` a component during bundle creation

**Comment by rjferguson21** [comment]
@UncleGedd I'd love to try to implement that.  

I believe the there are technically two pieces.
* prevent a particular zarf component that is `required: false, default:  true`, from deploying at bundle deploy time. 
* prevent the same component from being included in the bundle at create time

I think it would be reasonable to do the first bullet, and tackle the second at a later date. /cc @zachariahmiller

**Comment by UncleGedd** [comment]
Hey @rjferguson21 looks like Zarf is [refactoring](https://github.com/defenseunicorns/zarf/pull/2211) `required` vs `optional` key on their side. I recommend waiting until that behavior is finalized before implementing this

**Comment by UncleGedd** [comment]
Closing in favor of https://github.com/defenseunicorns/uds-core/pull/586

**Pull request closed without merging**
